spring:
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    datasource:
        url: jdbc:postgresql://localhost:5432/tortycolis
        username: postgres
        password: mysecretpassword